export const CALCULATORS = {
  coneArea: "Cone Area Calculator",
  cubeArea: "Cube Area Calculator",
  rectangleArea: "Rectangular Area Calculator",
  cylindricalTankArea: "Cylindrical Tank Area Calculator",
  parallelogramArea: "Parallelogram Area Calculator",
  ellipseArea: "Ellipse Area Calculator",
  trapezoidArea: "Trapezoid Area Calculator",
  triangleArea: "Triangle Area Calculator",
  circleArea: "Circle Area Calculator",
  sectorArea: "Sector Area Calculator",

  ballSurfArea: "Ball Surface Area Calculator",
  sphericalCapSurfArea: "Spherical Cap Surface Area Calculator",
  capsuleSurfArea: "Capsule Surface Area Calculator",
  conicalFrustrumSurfArea: "Conical Frustrum Surface Area Calculator",
  squarePyramidSurfArea: "Square Pyramid Surface Area Calculator",
  ellipsoidSurfArea: "Ellipsoid Surface Area Calculator",

  sphereVol: "Sphere Volume Calculator",
  coneVol: "Cone Volume Calculator",
  cubeVol: "Cube Volume Calculator",
  cylinderVol: "Cylinder Volume Calculator",
  rectangleVol: "Rectangle Volume Calculator",
  capsuleVol: "Capsule Volume Calculator",
  sphericalCapVol: "Spherical Cap Volume Calculator",
  squarePyramidVol: "Square Pyramid Volume Calculator",
  ellipsoidVol: "Ellipsoid Volume Calculator",
  tubeVol: "Tube Volume Calculator",
  conicalFrustrumVol: "Conical Frustrum Volume Calculator",

  bodyMassIndex: "Body Mass Index Calculator",
  leanBodyMass: "Lean Body Mass Calculator",
  regularCycleOvulation: "Regular Cycle Ovulation",
  leanBodyMassBoer: "Lean Body Mass Boer Formular",
  leanBodyMassJames: "Lean Body Mass James Formular",
  leanBodyMassHume: "Lean Body Mass Hume Formular",
  marginOfError: "Margin of Error Calculator",
  sampleSize: "Sample Size Calculator",

  concreteSquareFooting: "Concrete Square Footing",
  circularSlap: "Circular Slap Calculator",
  curbAndGutterBarrier: "Curb And Gutter Barrier Calculator",
  stairsConcrete: "Stairs Concrete Calculator",
  holeColumn: "Hole Column Calculator",

  amortizedLoanFixedAmount: "Amortized Loan Fixed Amount Calculator",
  bondPayBackPredetermined: "Bond PayBack Predetermined Calculator",
  defearedPaymentsLumpsumAtMaturity:
    "Defeared Payments Lumpsum at Maturity Calculator",
  inflationCalculatorCpiData: "Inflation Calculator CPI Data",
  mortgagePayoffWithLoanTerm: "Mortgage Payoff With Loan Term Calculator",
  mortgagePayOffWithoutLoanTerm: "Mortgage Payoff Without Loan Term Calculator",
  payBackACertainAmount: "PayBack a Certain Amount Calculator",
  paybackWithinTimeFrame: "Payback Within Timeframe Calculator",
  presentValue: "Present Value Calculator",
  presentValueOfPeriodicalDeposit:
    "Present Value of Periodical Deposit Calculator",
  profitMargin: "Profit Margin Calculator",
  stockTradingMargin: "Stock Trading Margin Calculator",
};

export const BUTTONS = {
  calculate: "Calculate",
};

export const PLACEHOLDERS = {
  unit: "Unit",
  number: "0",
  gender: "Gender",
};

export const LABELS = {
  radius: "Radius",
  baseRadius: "Base Radius",
  topRadius: "Top Radius",
  bottomRadius: "Bottom Radius",
  ballRadius: "Ball Radius",
  axis: "Axis",
  axis1: "Axis1",
  axis2: "Axis2",
  axis3: "Axis3",
  unit: "Unit",
  length: "Length",
  width: "Width",
  edgeLength: "Edge Length",
  baseEdge: "Base Edge",
  height: "Height",
  weight: "Weight",
  mass: "Mass",
  days: "Days",
  cycleDays: "Cycle Days",
  date: "Date",
  previousCycleStartDate: "Previous Cycle Start Date",
  gender: "Gender",
  populationSize: "Population Size",
  zScore: "Z-Score",
  marginOfError: "Margin of Error",
  standardDeviation: "Standard Deviation",
  sampleSize: "Sample Size",
  breadth: "Breadth",
  semiMajorAxesA: "Semi Major Axes A",
  semiMajorAxesB: "Semi Major Axes B",
  base: "Base",
  base1: "Base 1",
  base2: "Base 2",
  sideA: "Side A",
  sideB: "Side B",
  sideC: "Side C",
  angle: "Angle",
  outerDiameter: "Outer Diameter",
  innerDiameter: "Inner Diameter",
  quantity: "Quantity",
  curbDepth: "Curb Depth",
  curbHeight: "Curb Height",
  flagThickness: "Flag Thickness",
  gutterWidth: "Gutter Width",
  run: "Run",
  rise: "Rise",
  platformDepth: "Platform Depth",
  steps: "Steps",
  diameter: "Diameter",
  months: "Months",
  interestRate: "Interest Rate",
  year: "Year",
  creditCardBalance: "Credit Card Balance",
  totalPaymentsperYear: "Total Payments",
  paymentsMade: "Payments Made",
  loanAmount: "Loan Amount",
  monthlyPayment: "Monthly Payment",
  principalBalance: "Principal Balance",
  presentValue: "Present Value",
  numberOfMonths: "Number of Months",
  numberOfYears: "Number of Years",
  predeterminedAmount: "Predetermined Amount",
  periodDeposit: "Peroid Deposit",
  salesRevenue: "Sales Revenue",
  cost: "Cost",
  marginRequirement: "Margin Requirement",
  stockPrice: "Stock Price",
  shares: "Shares",
  currentPrice: "Current Price",
  priceInBase: "Price in Base",
};

export const IDS = {
  length: "length",
  w: "width",
};

export const INPUT_TYPE = {
  text: "text",
  number: "number",
  button: "button",
  date: "date",
  range: "range",
  submit: "submit",
};
