export const CALCULATORS = {
  coneArea: "Cone Area Calculator",
  cubeArea: "Cube Area Calculator",
  rectangleArea: "Rectangular Area Calculator",
  cylindricalTankArea: "Cylindrical Tank Area Calculator",
  parallelogramArea: "Parallelogram Area Calculator",
  ellipseArea: "Ellipse Area Calculator",
  trapezoidArea: "Trapezoid Area Calculator",
  triangleArea: "Triangle Area Calculator",
  circleArea: "Circle Area Calculator",
  sectorArea: "Sector Area Calculator",

  ballSurfArea: "Ball Surface Area Calculator",
  sphericalCapSurfArea: "Spherical Cap Surface Area Calculator",
  capsuleSurfArea: "Capsule Surface Area Calculator",
  conicalFrustrumSurfArea: "Conical Frustrum Surface Area Calculator",
  squarePyramidSurfArea: "Square Pyramid Surface Area Calculator",
  ellipsoidSurfArea: "Ellipsoid Surface Area Calculator",

  sphereVol: "Sphere Volume Calculator",
  coneVol: "Cone Volume Calculator",
  cubeVol: "Cube Volume Calculator",
  cylinderVol: "Cylinder Volume Calculator",
  rectangleVol: "Rectangle Volume Calculator",
  capsuleVol: "Capsule Volume Calculator",
  sphericalCapVol: "Spherical Cap Volume Calculator",
  squarePyramidVol: "Square Pyramid Volume Calculator",
  ellipsoidVol: "Ellipsoid Volume Calculator",
  tubeVol: "Tube Volume Calculator",
  conicalFrustrumVol: "Conical Frustrum Volume Calculator",

  bodyMassIndex: "Body Mass Index Calculator",
  leanBodyMass: "Lean Body Mass Calculator",
  regularCycleOvulation: "Regular Cycle Ovulation Calculator",
  leanBodyMassPetersFormula: "Lean Body Mass Peter's Formula Calculator",
  bodyMassIndexMethodTwo: "Body Mass Index Method Two Calculator",
  bMRKatchMcArdle: "BMR Katch McArdle Calculator",
  bloodAlcoholContent: "Blood Alcohol Content Calculator",
  usCustomarySystemBfc: "US Customary System BFC Calculator",
  internationalSystemBfc: "International System BFC Calculator",
  bodyFatPercentageBmi: "Body Fat Percentage BMI Calculator",
  dueDateNaegeleRule: "Due Date Naegele Rule Calculator",
  peroidCalculator: "Peroid Calculator",
  dueDateMittendorfWilliam: "Due Date Mittendorf William Calculator",
  duBoisBodySurfaceArea: "DuBois Body Surface Area Calculator",
  wholeBodyMassFormula: "Whole Body Mass Formula Calculator",
  mostellerBodySurfaceArea: "Mosteller Body Surface Area Calculator",
  haycockBodySurfaceArea: "Haycock Body Surface Area Calculator",
  gehanAndGeorgeSurfaceArea: "Gehan And George Surface Area Calculator",
  boydFormulaSurfaceArea: "Boyd Formula Surface Area Calculator",
  takahiraBodySurfaceArea: "Takahira Body Surface Area Calculator",
  takaSchlichBodySurfaceArea: "Taka Schlich Body Surface Area Calculator",
  singlePointWithKnownSlope: "Single Point With Known Slope Calculator",
  probabilityOfASeriesOfIndpendentEvents:
    "Probability of a Series of Indpendent Events Calculator",

  marginOfError: "Margin of Error Calculator",
  sampleSize: "Sample Size Calculator",
  probablityOfTwoEvents: "Probablity of Two Events Calculator",
  probablitySolverForTwoEvents: "Probablity Solver For Two Events Calculator",

  concreteSquareFooting: "Concrete Square Footing Calculator",
  circularSlap: "Circular Slap Calculator",
  curbAndGutterBarrier: "Curb And Gutter Barrier Calculator",
  stairsConcrete: "Stairs Concrete Calculator",
  holeColumn: "Hole Column Calculator",
  slopeCalculatorForTwoKnownPoints: "Slope Calculator For Two Known Points",
  elapsedTimeMethod: "Elapsed Time Method Calculator",
  trapSpeedMethod: "Trap Speed Method Calculator",
  parrallelResitor: "Parrallel Resitor Calculator",
  seriesResistor: "Series Resistor Calculator",
  conductorResitor: "Conductor Resitor Calculator",
  horsepowerCalculation: "Horsepower Calculator",
  websiteBandwidth: "Website Bandwidth Calculator",
  hostingBandwidth: "Hosting Bandwidth Calculator",
  fujimotoFormulaSurfaceArea: "Fujimoto Formula Surface Area Calculator",
  dueDateParikhsRule: "Due Date Parikh's Rule Calculator",
  dueDateWoodsRule: "Due Date Woods Rule Calculator",
  bmrMifflinJeorEquation: "BMR Mifflin Jeor Equation Calculator",
  bmrMifflinHarrisBenedict: "BMR Mifflin Harris Benedict Calculator",

  amortizedLoanFixedAmount: "Amortized Loan Fixed Amount Calculator",
  bondPayBackPredetermined: "Bond PayBack Predetermined Calculator",
  defearedPaymentsLumpsumAtMaturity:
    "Defeared Payments Lumpsum at Maturity Calculator",
  inflationCalculatorCpiData: "Inflation Calculator CPI Data",
  mortgagePayoffWithLoanTerm: "Mortgage Payoff With Loan Term Calculator",
  mortgagePayOffWithoutLoanTerm: "Mortgage Payoff Without Loan Term Calculator",
  payBackACertainAmount: "PayBack a Certain Amount Calculator",
  paybackWithinTimeFrame: "Payback Within Timeframe Calculator",
  presentValue: "Present Value Calculator",
  presentValueOfPeriodicalDeposit:
    "Present Value of Periodical Deposit Calculator",
  profitMargin: "Profit Margin Calculator",
  stockTradingMargin: "Stock Trading Margin Calculator",
};

export const BUTTONS = {
  calculate: "Calculate",
};

export const PLACEHOLDERS = {
  unit: "Unit",
  number: "0",
  gender: "Gender",
  type: "Type",
  method: "Method",
  date: "Date",
};

export const LABELS = {
  radius: "Radius",
  baseRadius: "Base Radius",
  topRadius: "Top Radius",
  bottomRadius: "Bottom Radius",
  ballRadius: "Ball Radius",
  axis: "Axis",
  axis1: "Axis1",
  axis2: "Axis2",
  axis3: "Axis3",
  unit: "Unit",
  length: "Length",
  width: "Width",
  edgeLength: "Edge Length",
  baseEdge: "Base Edge",
  height: "Height",
  weight: "Weight",
  mass: "Mass",
  days: "Days",
  cycleDays: "Cycle Days",
  date: "Date",
  previousCycleStartDate: "Previous Cycle Start Date",
  gender: "Gender",
  populationSize: "Population Size",
  zScore: "Z-Score",
  marginOfError: "Margin of Error",
  standardDeviation: "Standard Deviation",
  sampleSize: "Sample Size",
  breadth: "Breadth",
  semiMajorAxesA: "Semi Major Axes A",
  semiMajorAxesB: "Semi Major Axes B",
  base: "Base",
  base1: "Base 1",
  base2: "Base 2",
  sideA: "Side A",
  sideB: "Side B",
  sideC: "Side C",
  angle: "Angle",
  outerDiameter: "Outer Diameter",
  innerDiameter: "Inner Diameter",
  quantity: "Quantity",
  curbDepth: "Curb Depth",
  curbHeight: "Curb Height",
  flagThickness: "Flag Thickness",
  gutterWidth: "Gutter Width",
  run: "Run",
  rise: "Rise",
  platformDepth: "Platform Depth",
  steps: "Steps",
  diameter: "Diameter",
  months: "Months",
  interestRate: "Interest Rate",
  year: "Year",
  creditCardBalance: "Credit Card Balance",
  totalPaymentsperYear: "Total Payments",
  paymentsMade: "Payments Made",
  loanAmount: "Loan Amount",
  monthlyPayment: "Monthly Payment",
  principalBalance: "Principal Balance",
  presentValue: "Present Value",
  numberOfMonths: "Number of Months",
  numberOfYears: "Number of Years",
  predeterminedAmount: "Predetermined Amount",
  periodDeposit: "Peroid Deposit",
  salesRevenue: "Sales Revenue",
  cost: "Cost",
  marginRequirement: "Margin Requirement",
  stockPrice: "Stock Price",
  shares: "Shares",
  currentPrice: "Current Price",
  priceInBase: "Price in Base",
  fat: "Fat",
  hoursOfDrinking: "Hours of Drinking",
  minutesOfDrinking: "Minutes of Drinking",
  numberOfStandardDrinks: "Number of Standard Drinks",
  neck: "Neck",
  abdomen: "Abdomen",
  hip: "Hip",
  waist: "Waist",
  age: "Age",
  firstDateofLastPeriod: "First Data of Last Period",
  method: "Method",
  lastPeriodDays: "Last Period Days",
  cycleLength: "Cycle Length",
  y1: "Y 1",
  y2: "Y 2",
  distance: "Distance",
  x1: "X 1",
  x2: "X 2",
  slope: "Slope",
  eventA: "Event A",
  eventB: "Event B",
  aRepeatTimes: "A Repeat Times",
  bRepeatTimes: "B Repeat Times",
  type: "Type",
  time: "Time",
  speed: "Speed",
  resistanceValues: "Resistance Values",
  redundancyFactor: "redundancyFactor",
  conductivity: "Conductivity",
  force: "Force",
  pageViews: "Page Views",
  pageSize: "Page Size",
  monthlyUsage: "Monthly Usage",
  probabilityOfA: "Probability of A",
  probabilityOfB: "Probability of B",
  probabilityOfANotOccuring: "Probability of A not Occuring",
  probabilityOfBNotOccuring: "Probability of B not Occuring",
  probabilityOfAAndBBothOccuring: "Probability of A and B both Occuring",
  probabilityThatAOrBOrBothOccur: "Probability that A or B or both Occur",
  probabilityOfNeitherANorBOccuring: "Probability of Neither A nor B Occuring",
  probabilityThatAOrBOccursButNotBoth:
    "Probability that A or B Occurs but not both",
};

export const IDS = {
  length: "length",
  w: "width",
};

export const INPUT_TYPE = {
  text: "text",
  number: "number",
  button: "button",
  date: "date",
  range: "range",
  submit: "submit",
};
